/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/xlWxchG1FJg
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Slider } from "@/components/ui/slider";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import React, { useEffect, useState } from "react";
import DailyMetricsCard from "./DailyMetricsCard";

export function Questionnaire() {
  return (
    <div className="flex flex-col md:flex-row flex-1 p-3 md:p-8 gap-8">
      <div className="md:w-1/3 grid gap-4">
        <Card>
          <CardHeader>
            <CardTitle>Daily Questionnaire</CardTitle>
          </CardHeader>
          <CardContent>
            <form className="grid gap-4">
              <div className="grid gap-2">
                <Label htmlFor="mood">Mood</Label>
                <Select defaultValue="good">
                  <SelectTrigger id="mood">
                    <SelectValue placeholder="Select mood" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="good">Good</SelectItem>
                    <SelectItem value="neutral">Neutral</SelectItem>
                    <SelectItem value="bad">Bad</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="grid gap-2">
                <Label htmlFor="energy">Energy Level</Label>
                <Slider id="energy" defaultValue={[50]} />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="soreness">Soreness</Label>
                <Slider id="soreness" defaultValue={[25]} />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="sleep">Sleep Quality</Label>
                <Select defaultValue="good">
                  <SelectTrigger id="sleep">
                    <SelectValue placeholder="Select sleep quality" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="good">Good</SelectItem>
                    <SelectItem value="average">Average</SelectItem>
                    <SelectItem value="poor">Poor</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="grid gap-2">
                <Label htmlFor="reflection">Reflection</Label>
                <Textarea id="reflection" placeholder="How are you feeling today?" className="min-h-[100px]" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="jump1">Jump 1</Label>
                <Input id="jump1" type="number" placeholder="Enter jump 1 height" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="jump2">Jump 2</Label>
                <Input id="jump2" type="number" placeholder="Enter jump 2 height" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="jump3">Jump 3</Label>
                <Input id="jump3" type="number" placeholder="Enter jump 3 height" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="squat-velocity">Squat Velocity</Label>
                <Input id="squat-velocity" type="number" placeholder="Enter squat velocity" />
                <div className="flex items-center gap-2">
                  <Checkbox id="opt-out-squat" />
                  <Label htmlFor="opt-out-squat">Opt out of squat velocity</Label>
                </div>
              </div>
              <Button type="submit" className="w-full ">
                Submit
              </Button>
            </form>
          </CardContent>
        </Card>
      </div>
      <div>
        <DailyMetricsCard />
      </div>
    </div>
  );
}

function FlagIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  );
}

function FrownIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M16 16s-1.5-2-4-2-4 2-4 2" />
      <line x1="9" x2="9.01" y1="9" y2="9" />
      <line x1="15" x2="15.01" y1="9" y2="9" />
    </svg>
  );
}

function SmileIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M8 14s1.5 2 4 2 4-2 4-2" />
      <line x1="9" x2="9.01" y1="9" y2="9" />
      <line x1="15" x2="15.01" y1="9" y2="9" />
    </svg>
  );
}
